server:
  port: 8080
spring:
  profiles:
    #active: test
    include: sharding-alarm
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 14
  main:
    allow-bean-definition-overriding: true
  application:
    name: test
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 192.168.133.130


