server:
  port: 8080
spring:
  cache:
    type: redis
  redis:
    host: 172.16.8.39
    port: 6379
    password: AdlKqNyjkdzAOyJUgX
    database: 14
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.133.129:3306/sharding?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      #未配置分片规则的表将通过默认数据源定位
      default-data-source-name: ds
      # 读写分离
      #      master-slave-rules:
      #        ds0:
      #          master-data-source-name: salve0
      #          slave-data-source-names: salve1,salve2
      #          # 轮询round_robin 随机(random)
      #          load-balance-algorithm-type: round_robin
      #          #load-balance-algorithm-class-name= #从库负载均衡算法类名称。该类需实现MasterSlaveLoadBalanceAlgorithm接口且提供无参数构造器
      #          #sharding.jdbc.config.sharding.master-slave-rules.<master-slave-data-source-name>.load-balance-algorithm-type= #从库负载均衡算法类型，
      #          name: ds0
      tables:
        sharding:
          actualDataNodes: ds.sharding_$->{2023}0$->{1..3}
          #          # 生成主键方式SNOWFLAKE何UUID
          keyGenerator:
            column: id
            type: SNOWFLAKE
          tableStrategy:
            standard:
              shardingColumn: time,startTime,endTime #分表字段
              precise-algorithm-class-name: com.lgq.sharding.config.MyPreciseShardingAlgorithm #自定义分表策略
              range-algorithm-class-name: com.lgq.sharding.config.MyPreciseShardingAlgorithm
        student:
          actualDataNodes: ds.student_$->{2023}0$->{1..3}
          #          # 生成主键方式SNOWFLAKE何UUID
          keyGenerator:
            column: id
            type: SNOWFLAKE
          tableStrategy:
            standard:
              shardingColumn: time #分表字段
              precise-algorithm-class-name: com.lgq.sharding.config.MyPreciseShardingAlgorithm #自定义分表策略
              rangeAlgorithmClassName: com.lgq.sharding.config.MyPreciseShardingAlgorithm
    props:
      sql:
        show: true
